### ISSUE TITLE
Broken links for all ThreeD transforms in the user manual

### ISSUE THREAD

**Issue by alexDarcy** [diagrams/diagrams-doc#76]
All functions from Diagrams.ThreeD.Transforms redirections to Diagrams.ThreeD. For example, `reflectAbout` redirects to 

http://projects.haskell.org/diagrams/haddock/Diagrams-ThreeD.html#v:reflectAbout

(which is wrong) instead of 

http://projects.haskell.org/diagrams/haddock/Diagrams-ThreeD-Transform.html#v:reflectAbout

**Comment by byorgey** [comment]
I think this is happening because `Diagrams.ThreeD` re-exports `reflectAbout`, but it does so by re-exporting the entire `Diagrams.ThreeD.Transform` module, so the Haddock documentation for `Diagrams.ThreeD` does not actually show `reflectAbout`.  We need a more nuanced way to decide how to generate links.  Right now it just searches for modules exporting a given name and links to the first one it finds.  One simple heuristic would be to always prefer more specific modules, i.e. if X.Y and X.Y.Z both export `foo`, then prefer linking to X.Y.Z.

**Comment by byorgey** [comment]
Fixed (for now) by https://github.com/diagrams/diagrams-doc/commit/863f6b78967272112054db877d9e0c1f3aec638c
